### ISSUE TITLE
Not compiling with ESPHome 2025.7.4 on docker

### ISSUE THREAD

**Issue by michaeleverist** [awulf/Actron485#4]
Hello,

I tried pulling your latest version to fix the deprecated messages in ESPHome and am having trouble compiling it now with ESPHome 2025.7.4.  I have tried cloning the repo from commit i was using but still having the same issue and I'm thinking the only other thing could be the version of ESPHome (Running on docker - ghcr.io/esphome/esphome:latest ).

All paths, etc are identical to the previous working setup and i have deleted the .esphome cache etc - do you have any other suggestions?

thanks in advance.
``` 
substitutions:
  device_name: "actron-aircon"
  friendly_name: "actron_aircon"

esp32: 
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: /config/Actron485/components
  # - source:
  #     type: git
  #     url: https://github.com/awulf/Actron485
  #     ref: f605458
  #   components: [actron485]



#################################
esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  platformio_options:
    lib_extra_dirs: /config/
  libraries:
    - Actron485  
  ```

```
INFO ESPHome 2025.7.4
INFO Reading configuration /config/actron-aircon.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing actron-aircon (board: esp32-c3-devkitm-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50302.0 (5.3.2) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 13.2.0+20240530
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.10
|-- ArduinoJson @ 7.4.2
Compiling .pioenvs/actron-aircon/src/esphome/components/actron485/actron485_climate.cpp.o
Compiling .pioenvs/actron-aircon/src/esphome/components/actron485/utilities.cpp.o
Compiling .pioenvs/actron-aircon/src/esphome/components/actron485/zone_climate.cpp.o
In file included from src/esphome/components/actron485/utilities.cpp:1:
src/esphome/components/actron485/utilities.h:3:10: fatal error: Actron485.h: No such file or directory

*************************************************************************
* Looking for Actron485.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Actron485.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKActron485.h
*
*************************************************************************

    3 | #include "Actron485.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
Compiling .pioenvs/actron-aircon/src/esphome/components/actron485/zone_fan.cpp.o
*** [.pioenvs/actron-aircon/src/esphome/components/actron485/utilities.cpp.o] Error 1
In file included from src/esphome/components/actron485/zone_climate.cpp:1:
src/esphome/components/actron485/utilities.h:3:10: fatal error: Actron485.h: No such file or directory

*************************************************************************
* Looking for Actron485.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Actron485.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKActron485.h
*
*************************************************************************

    3 | #include "Actron485.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/actron-aircon/src/esphome/components/actron485/zone_climate.cpp.o] Error 1
In file included from src/esphome/components/actron485/zone_fan.cpp:2:
src/esphome/components/actron485/utilities.h:3:10: fatal error: Actron485.h: No such file or directory

*************************************************************************
* Looking for Actron485.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Actron485.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKActron485.h
*
*************************************************************************

    3 | #include "Actron485.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/actron-aircon/src/esphome/components/actron485/zone_fan.cpp.o] Error 1
In file included from src/esphome/components/actron485/actron485_climate.cpp:1:
src/esphome/components/actron485/actron485_climate.h:9:10: fatal error: Actron485.h: No such file or directory

*************************************************************************
* Looking for Actron485.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Actron485.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKActron485.h
*
*************************************************************************

    9 | #include "Actron485.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/actron-aircon/src/esphome/components/actron485/actron485_climate.cpp.o] Error 1
========================== [FAILED] Took 5.04 seconds ==========================


```

**Comment by awulf** [comment]
I think where it's failing to compile for you is 
```
framework:
    type: esp-idf
```
needs to be 
```
framework:
    type: arduino
```
Currently there some arduino specific things being used, which I do want to get around in the future to make it more flexible.

But right now something has changed in ESPHome 2025.7.x where it this integration is broken anyway. The data coming in on the serial port is no longer timed/buffered as it once was, and the Actron uses timed messages. I have an idea how to fix it, first step was to add more robustness and it works a bit now, which is the last commit. Second step to try is to implement another faster task using xTaskCreate to capture the serial data quicker. For now I'm leaving my instance it at `esphome/esphome:2025.6` until I have time to work on it. Maybe even changing the code to work with esp-idf could fix it.

**Comment by awulf** [comment]
I can replicate your problem with the folder structure. Rather than putting the `actron485` folder in the esphome `config` folder, named `esphome` in your screen shot, you made a `config` folder inside. You can either 
1. Move `actron485` to `./esphome` and change `path: config/actron485/components/` to `path: /config/actron485/components/`
2. Or change the `lib_extra_dirs: /config/` to `lib_extra_dirs: /config/config/`

Also for any future posting multi-line code blocks in GitHub use the three ticks ``` at the start and end. I have fixed it up for you in your comment.

**Comment by AJ240-Aus** [comment]
Sorry for all the noob questions, still having issues. Really keen to get this working.
Do I have the files in the correct location now ? Do I have all the required files ?

Could not find directory '/config/actron485/components/'. 

<img width="857" height="659" alt="Image" src="https://github.com/user-attachments/assets/98556039-3a36-4446-b2a1-31b684faaf4b" />

'''esphome:
  name: actron-485
  friendly_name: Actron-RS485
  platformio_options:
    lib_extra_dirs: /config/
  libraries:
    - Actron485

external_components:
  - source:
      type: local
      path: /config/actron485/components/

esp32:
  board: esp32dev
  framework:
    type: arduino
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxx"

ota:
  - platform: web_server
    password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rs485 Fallback Hotspot"
    password: "xxxxxxxxxxxxxx"

web_server:
  port: 80

captive_portal:


  
# Adds fan component per zone (required)
fan:

# UART settings for Actron485 (required)
uart:
  rx_pin: GPIO27 #27 
  tx_pin: GPIO26 #26
  baud_rate: 4800

climate:
  - platform: Actron485
    name: "Actron Climate Controller"
    write_enable_pin: GPIO25 # Write Enable pin for the RS-485 communication
    esp_fan_available: true # For Systems with ESP Auto mode, adds Auto fan mode.
    logging_mode: ALL
    zones:
      - number: 1
        name: Living
      - number: 2
        name: Jan
      - number: 3
        name: Master Bedroom
      - number: 4
        name: Bedrooms
'''

**Comment by awulf** [comment]
> Sorry for all the noob questions, still having issues. Really keen to get this working. Do I have the files in the correct location now ? Do I have all the required files ?
> 
> Could not find directory '/config/actron485/components/'.

Looking at your screenshot you've moved `actron485` into a hidden folder `.esphome` try moving it up a level so it's in the `esphome` folder. The `actron485` folder should be in the same folder as your `.yaml` file

**Comment by AJ240-Aus** [comment]
No change unfortunatly.

<img width="1127" height="239" alt="Image" src="https://github.com/user-attachments/assets/2acd4c30-f63f-4c60-b697-7e57b9f40f95" />

<img width="747" height="653" alt="Image" src="https://github.com/user-attachments/assets/f5b0aeb9-ff8e-4f81-9988-8522810054c6" />

**Comment by AJ240-Aus** [comment]
That fixed that issue, and I am now back to original circular import issue .

<img width="1168" height="283" alt="Image" src="https://github.com/user-attachments/assets/2b75ceb1-3153-4eae-86ec-5e58a7c6ce2e" />

**Comment by awulf** [comment]
> That fixed that issue, and I am now back to original circular import issue .

I think you'll need to find the absolute path for your installation. Is it running in docker? Or how have you got ESPHome running?
If docker find out the `Working Dir`, you might be able to spot it in the logs. E.g. mine shows 
```
2025-09-07 16:21:41,989 INFO Running command 'esphome --dashboard run /config/actron-remote-poe.yaml --device 192.168.34.148'
```
Which shows the absolute path to my yaml file, showing that `/config/` is the folder path to it.

So what ever you see in yours change this to what yours is
`lib_extra_dirs: /config/`

Maybe some info here will help https://esphome.io/components/external_components/

**Comment by AJ240-Aus** [comment]
Still no joy even after trying /config/esphome/ I may have to give up on this rather than troubling you any further. I just don't understand enough of what is happening in the background to troubleshoot this properly.

**Comment by AJ240-Aus** [comment]
This what I found on circular imports. What I am not sure about is how the folder paths effect this behaviour.
To my limited knowledge, it looks like something is looking for CAPITAL "C" Climate rather than lowercase 'c" climate. ??

esphome.components.climate' has no attribute 'Climate' (most likely due to a circular import). Did you mean: 'climate'?

A circular import in ESPHome, similar to Python, occurs when two or more custom components or configuration sections mutually depend on each other through their includes or references. This creates a loop where each part attempts to load something from the other before it is fully defined, leading to compilation errors or unexpected behavior.

Causes of Circular Imports in ESPHome:
Mutual !include statements:
If file_a.yaml includes file_b.yaml, and file_b.yaml also includes file_a.yaml, a circular dependency is formed.

Component dependencies:
A custom component might require an id or !include from another component, which in turn requires something from the first component.

Template references:
Complex template structures where templates refer to each other in a circular manner can also lead to this issue.

Fixing Circular Imports in ESPHome:
Refactor your configuration:
Break down large files: Divide your configuration into smaller, more focused files.

Centralize common elements: Create a dedicated file for shared components, ids, or templates that can be included by other files without creating circular references.

Re-evaluate dependencies: Determine if all !include statements or id references are truly necessary or if they can be restructured.
Use ids for forward references:
When a component needs to refer to another component that is defined later in the configuration, use its id to reference it. This allows ESPHome to resolve the dependency once all components are defined.

Ensure logical flow:
Organize your YAML files and component definitions in a way that establishes a clear, hierarchical dependency structure, avoiding backward or circular references.

**Comment by awulf** [comment]
When I have time i’ll spin up a Virtual Machine with Home Assistant OS and see if i can replicate your issues. It’ll be some sort of issue with paths.

**Comment by AJ240-Aus** [comment]
I appreciate the effort. May help some others users if this OS related.

**Comment by awulf** [comment]
Installed Home Assistant OS on a VM with ESPHome Builder Add-on the following works for me

```
esphome:
  name: actrontest
  friendly_name: ActronTest
  platformio_options:
    lib_extra_dirs: /config/esphome
  libraries:
    - Actron485

external_components:
  - source:
      type: local
      path: /config/esphome/actron485/components/
```

Also you need to change your config A to lower case a for climate
```
climate:
  - platform: actron485
```

**Comment by AJ240-Aus** [comment]
I made the changes above but I am still getting the error with circular import from climate.py

 File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/esphome/actron485/components/climate.py", line 47, in <module>
    Actron485Climate = actron485_ns.class_("Actron485Climate", climate.Climate, cg.Component)
                                                               ^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'esphome.components.climate' has no attribute 'Climate' (most likely due to a circular import). Did you mean: 'climate'?

**Comment by awulf** [comment]
> I made the changes above but I am still getting the error with circular import from climate.py

Maybe you accidentally modified a file inside the project, so 

1. Delete the actron485 folder
2. Checkout a new copy with the terminal command `git clone https://github.com/awulf/Actron485.git actron485` inside the `esphome` folder
3. Clean the build files 

<img width="789" height="588" alt="Image" src="https://github.com/user-attachments/assets/2d8d9f57-fae4-4248-bb7f-fe0dbc7c9906" />

**Comment by awulf** [comment]
Closing issue since it does compile on 2025.7.4, and the latest 2025.9.3
